"""Hand-written labelled cases for the memory policy (docs/AUTO_MEMORY_DESIGN.md, D1-D3; unit A1), in both directions: what must be
caught, and the plain lines that must not be. Written by the same author as the detectors, so they show that the rules do what they say
and not how they will do on real conversations; the real measure is `python diya_autonomy_bench.py` (unit A6). Every secret below is
invented or a published test value.
"""

# (text, the kind it must be called)
SECRETS = [
    ("my password is hunter2", "password"),
    ("the wifi password is sunshine123", "password"),
    ("wifi password is on the fridge", "password"),
    ("my phone pin is 4821", "password"),
    ("the OTP is 482913", "password"),
    ("the one-time code from the bank is 559012", "password"),
    ("verification code 330918 came by text", "password"),
    ("the CVV is 123", "password"),
    ("passphrase: correct horse battery staple", "password"),
    ("uses the credentials admin and admin", "credential"),
    ("the api key is stored in the .env file", "token"),
    ("OpenAI key sk-abcdefghijklmnopqrstuvwx", "token"),
    ("github token ghp_abcdefghijklmnopqrstuvwxyz0123456789", "token"),
    ("AWS key AKIAIOSFODNN7EXAMPLE", "token"),
    ("Slack token xoxb-1234567890-abcdefghij", "token"),
    ("jwt eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxMjM0NTY3ODkwIn0.dummysignature", "token"),
    ("d41d8cd98f00b204e9800998ecf8427e", "token"),
    ("session id a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7f8", "token"),
    ("the recovery phrase is written on a card in the safe", "recovery"),
    ("my seed phrase starts with abandon", "recovery"),
    ("card number 4111 1111 1111 1111", "card"),
    ("pays with 4242-4242-4242-4242", "card"),
    ("bank account number is 123456789012", "card"),
    ("routing number 021000021", "card"),
    ("Aadhaar 1234 5678 9012", "id"),
    ("SSN 123-45-6789", "id"),
    ("PAN is ABCDE1234F", "id"),
    ("passport number K1234567", "id"),
    ("driving licence number MH12 20190012345", "id"),
    ("IBAN GB82WEST12345698765432", "id"),
    # one for each word or shape the detector knows, so that dropping any of them is noticed
    ("the passcode is 0000", "password"),
    ("the security code on the back is on a sticker", "password"),
    ("the CVC is 456", "password"),
    ("the secret key lives in the vault", "token"),
    ("a private key is saved in the home folder", "token"),
    ("the access token is in the notes app", "token"),
    ("a bearer token expires every hour", "token"),
    ("the auth token is saved somewhere", "token"),
    ("the authentication token rotates weekly", "token"),
    ("has an Aadhaar card", "id"),
    ("has an Aadhar card", "id"),
    ("the PAN card is in the drawer", "id"),
    ("the PAN number is on the form", "id"),
    ("social security is needed for the form", "id"),
    ("the SSN is in the file", "id"),
    ("the national ID is in the locker", "id"),
    ("ref 2345-6789-0123 on the form", "id"),
    ("ref 123-45-6789 on the letter", "id"),
    ("github token ghp_abcdefghijklmnopqrstuvwxyz", "token"),
    ("Google key AIzaSyabcdefghijklmnopqrstuvwxyz", "token"),
    ("keeps Zk3pQ9vXw2LmN7rTy5HbJ8cDf4GsA1 somewhere", "token"),
    ("abcdefabcdefabcdefabcdefabcdefab", "token"),
    ("Amex 3782 822463 10005", "card"),
    ("a 13 digit card 4222222222222", "card"),
    ("a 19 digit card 6200000000000000000", "card"),
]

NOT_SECRETS = [
    "likes tea in the morning",
    "lives in Pune",
    "has a 3 year old cat named Pixel",
    "the dentist appointment is on Friday at 3pm",
    "pin code of the new flat is 411001",
    "was born in 1990",
    "flight AI 202 leaves on Friday at 6pm",
    "weighs 70 kg and is 175 cm tall",
    "wakes up at 6:30 on weekdays",
    "birthday is on 14 March 2003",
    "meeting is in room 405 on the second floor",
    "moved to the new office on 2026-10-14",
    "uses a tablet to read in the evening",
    "runs 5k every morning before work",
    "the project code name is bluebird",
    "favourite number is 7 and favourite colour is green",
    "sister Maya is visiting in May",
    "i like to go for a long walk in the park every morning before i go to work and then have tea",
    "prefers concise answers",
    "is learning to play the guitar",
    "the train number is 12345 and leaves at noon",
    "has two brothers and one sister",
    "works on a laptop with 16 GB of memory",
    "reads about 30 pages every night",
    "pins photos to the corkboard in the study",
    "abcdefabcdefabcdefabcdefabcdefa",
]

# (text, the class it must be called)
SENSITIVE = [
    ("is allergic to peanuts", "health"),
    ("takes metformin for diabetes", "health"),
    ("has asthma", "health"),
    ("sees a therapist on Tuesdays", "health"),
    ("takes pills at 8am", "health"),
    ("was prescribed antibiotics last week", "health"),
    ("is pregnant", "health"),
    ("earns 12 lakhs a year", "money"),
    ("owes his brother $500", "money"),
    ("has a home loan with a monthly EMI", "money"),
    ("pays Rs 500 for lunch every day", "money"),
    ("savings are about 2 lakhs", "money"),
    ("is going to court next month", "legal"),
    ("is going through a divorce", "legal"),
    ("talked to a lawyer about the lease", "legal"),
    ("lives at 14 Rose Street", "address"),
    ("home address is Flat 302 Green Park", "address"),
    ("the apartment number is 14", "address"),
    ("Maya's number is 98765 43210", "contact"),
    ("email is maya@example.com", "contact"),
    ("his phone number is on the invoice", "contact"),
    ("is Muslim", "belief"),
    ("voted in the last election", "belief"),
    ("is atheist", "belief"),
    # one for each word the detector knows
    ("was diagnosed last year", "health"),
    ("takes a daily medication", "health"),
    ("buys medicines on Sundays", "health"),
    ("was prescribed rest for a week", "health"),
    ("the dosage is twice a day", "health"),
    ("keeps a list of symptoms", "health"),
    ("had surgery last year", "health"),
    ("has had two surgeries", "health"),
    ("finished chemotherapy in May", "health"),
    ("had a miscarriage", "health"),
    ("survived cancer", "health"),
    ("has epilepsy", "health"),
    ("has depression", "health"),
    ("has anxiety", "health"),
    ("has bipolar", "health"),
    ("has schizophrenia", "health"),
    ("has ADHD", "health"),
    ("is autistic", "health"),
    ("is HIV positive", "health"),
    ("takes mental health days", "health"),
    ("the blood pressure is high", "health"),
    ("the blood sugar is high", "health"),
    ("the blood group is O positive", "health"),
    ("has a chronic back problem", "health"),
    ("has a sleep disorder", "health"),
    ("has a heart disease", "health"),
    ("gets injections monthly", "health"),
    ("takes antibiotics for a week", "health"),
    ("takes insulin every morning", "health"),
    ("is paid a good salary", "money"),
    ("the income is steady", "money"),
    ("keeps track of net worth", "money"),
    ("has a lot of debt", "money"),
    ("took a loan from the bank", "money"),
    ("has a mortgage", "money"),
    ("pays the EMI on the 5th", "money"),
    ("the credit score is good", "money"),
    ("owes his brother some money", "money"),
    ("the money is owed to him", "money"),
    ("went bankrupt once", "money"),
    ("keeps savings in a fixed deposit", "money"),
    ("the bank balance is low", "money"),
    ("filed the tax return", "money"),
    ("has investments in index funds", "money"),
    ("the phone cost ₹15000", "money"),
    ("the house is worth 3 crores", "money"),
    ("filed a lawsuit against the landlord", "legal"),
    ("was sued by a client", "legal"),
    ("is suing the airline", "legal"),
    ("was arrested once", "legal"),
    ("called the police about the noise", "legal"),
    ("has custody of the dog", "legal"),
    ("has a restraining order", "legal"),
    ("is waiting on immigration papers", "legal"),
    ("was convicted of speeding", "legal"),
    ("has a criminal record", "legal"),
    ("is out on bail", "legal"),
    ("met an attorney", "legal"),
    ("lives at the farm outside town", "address"),
    ("my  address is in the notes", "address"),
    ("the office is at 14 Rose Street", "address"),
    ("Maya's landline is 020-2567-1234", "contact"),
    ("is agnostic", "belief"),
    ("is Christian", "belief"),
    ("is Hindu", "belief"),
    ("is Sikh", "belief"),
    ("is Jewish", "belief"),
    ("is Buddhist", "belief"),
    ("is Catholic", "belief"),
    ("is gay", "belief"),
    ("is lesbian", "belief"),
    ("is bisexual", "belief"),
    ("is transgender", "belief"),
    ("is queer", "belief"),
    ("asked about sexual orientation", "belief"),
    ("likes to talk politics", "belief"),
    ("votes for the green party", "belief"),
    ("belongs to a certain caste", "belief"),
    ("the ethnicity is on the form", "belief"),
    ("faced racial abuse", "belief"),
    ("is very religious", "belief"),
]

# a text in two classes is called the first (the order is health, money, legal, address, contact, belief)
SENSITIVE_FIRST = [
    ("takes insulin and owes Rs 500", "health"),
    ("emailed the lawyer at maya@example.com", "legal"),
]

PLAIN = [
    "likes tea in the morning",
    "prefers concise answers",
    "sister Maya is visiting in May",
    "has a dentist appointment on Friday at 3pm",
    "works as a software engineer",
    "is learning to play the guitar",
    "lives in Pune",
    "has a cat named Pixel",
    "wakes up at 6:30 on weekdays",
    "wants to read more books this year",
    "drinks green tea after lunch",
    "uses a tablet to read in the evening",
    "runs 5k every morning",
    "is building a local AI assistant",
    "the book club meets on the first Sunday of the month",
]
