"""The research dossier's web page is generated from the same content as its PDF (dossier_content.py ->
render_html.py, render_pdf.py), so the two cannot drift, and the committed page cannot go stale.

What this proves: the page is exactly what the content produces (the check that used to be a human
remembering); every section, sub-heading, table, code block, timeline entry and source in the content reaches
the page; text is escaped so nothing in the content can inject markup while the content's own marks (bold,
code, italic) work; the page loads nothing from anywhere; and the content module and the page generator need
no PDF library, which the base install does not have.
"""
import html
import pathlib
import re
import subprocess
import sys
import types

import pytest

import dossier_content
import render_html

ROOT = pathlib.Path(__file__).resolve().parent.parent


def content(**overrides):
    """A tiny content module for the cases the real dossier does not happen to contain."""
    base = dict(
        SECTIONS=[], SOURCES=[], FOOTNOTE="A footnote.", EYEBROW="EYEBROW &middot; 2026", TITLE="Title", TAGLINE="The Tagline",
        SUBTITLE="A subtitle.", PILLS=["one"], SOURCES_HEADING="9 &middot; Sources",
    )
    base.update(overrides)
    return types.SimpleNamespace(**base)


def section(*blocks, intro=None):
    return {"num": 1, "id": "s1", "title": "First", "intro": intro, "blocks": list(blocks)}


def page(*blocks, **kw):
    return render_html.build(content(SECTIONS=[section(*blocks, **kw)]), style="")


# --- the committed page is the generated page -------------------------------------------------------

def test_the_committed_page_is_exactly_what_the_content_produces():
    committed = (ROOT / "truffle-research.html").read_text(encoding="utf-8")
    assert committed == render_html.build(), "run: python render_html.py"


def test_the_check_command_agrees(tmp_path):
    result = subprocess.run([sys.executable, str(ROOT / "render_html.py"), "--check"], cwd=ROOT, capture_output=True, text=True, timeout=60)
    assert result.returncode == 0 and "up to date" in result.stdout, result.stdout + result.stderr


def test_building_is_deterministic_and_the_page_is_utf8_with_lf_only():
    first, second = render_html.build(), render_html.build()
    assert first == second and first.endswith("</html>\n") and "\r" not in first
    assert first.encode("utf-8").decode("utf-8") == first


def test_the_page_says_it_is_generated_and_where_to_edit():
    assert "GENERATED by render_html.py from dossier_content.py" in render_html.build()


# --- everything in the content reaches the page --------------------------------------------------------

def test_every_section_and_source_of_the_real_dossier_is_on_the_page():
    rendered = render_html.build()
    assert rendered.count("<section ") == len(dossier_content.SECTIONS) == 11
    for sec in dossier_content.SECTIONS:
        assert f'<section id="{sec["id"]}">' in rendered
        assert f'href="#{sec["id"]}"' in rendered  # and it is in the sidebar
        assert render_html.inline(sec["title"]) in rendered
    body = rendered.split('<footer id="sources">')[1]
    for title, _description in dossier_content.SOURCES:
        assert render_html.inline(title) in body or html.escape(title) in body  # a bare address is a link, the rest is text
    assert len(re.findall(r"<li>", body)) == len(dossier_content.SOURCES)


def test_every_block_kind_the_real_dossier_uses_is_rendered_and_counted():
    rendered = render_html.build()
    kinds = {}
    for sec in dossier_content.SECTIONS:
        for block in sec["blocks"]:
            kinds[block[0]] = kinds.get(block[0], 0) + 1
    assert rendered.count('<div class="table-wrap">') == kinds["table"]
    assert rendered.count("<pre>") == kinds["code"]
    assert rendered.count('<ul class="timeline">') == kinds["timeline"]
    assert rendered.count('<div class="name-grid">') == kinds["namegrid"]
    assert rendered.count('<div class="fact-grid">') == kinds["facts"]
    assert rendered.count('<div class="callout warn">') == kinds["callout_warn"]
    assert rendered.count('<div class="callout">') == kinds["callout"]
    assert rendered.count('<h3 class="sub-head"') == kinds["h2"]
    assert rendered.count("<h4>") == kinds["h3"]


def test_every_table_cell_and_every_timeline_entry_of_the_real_dossier_is_on_the_page():
    rendered = render_html.build()
    for sec in dossier_content.SECTIONS:
        for block in sec["blocks"]:
            if block[0] == "table":
                for row in block[2]:
                    for cell in row:
                        assert render_html.inline(cell[5:] if str(cell).startswith("MONO:") else cell) in rendered
            if block[0] == "timeline":
                for date, title, _desc in block[1]:
                    assert html.escape(date) in rendered and render_html.inline(title) in rendered


def test_the_sidebar_lists_the_sections_in_order_and_the_sub_headings_under_theirs():
    rendered = render_html.build()
    nav = rendered.split('<nav class="toc"')[1].split("</nav>")[0]
    numbers = [int(n) for n in re.findall(r'<li><a href="#[a-z]+">(\d+)\. ', nav)]
    assert numbers == list(range(1, 12))
    assert 'class="sub"' in nav
    for anchor in re.findall(r'<li class="sub"><a href="#([^"]+)"', nav):
        assert f'id="{anchor}"' in rendered  # a sidebar link always has somewhere to go


# --- what goes in is escaped; the content's own marks work ---------------------------------------------

def test_text_is_escaped_so_content_cannot_inject_markup():
    rendered = page(("p", "1 < 2 and <script>alert(1)</script> & <b>not bold</b>"))
    assert "<script>" not in rendered and "&lt;script&gt;alert(1)&lt;/script&gt;" in rendered
    assert "&lt;b&gt;not bold&lt;/b&gt;" in rendered and "1 &lt; 2" in rendered
    assert "&amp; &lt;b" in rendered  # a bare ampersand


def test_an_entity_the_content_already_wrote_is_not_escaped_twice():
    rendered = page(("p", "Tom &amp; Jerry &middot; 2026 &#9679;"))
    assert "Tom &amp; Jerry &middot; 2026 &#9679;" in rendered and "&amp;amp;" not in rendered


def test_bold_code_and_italic_marks_work_and_nothing_else_becomes_a_tag():
    assert render_html.inline("a **bold** and `code` and _italic_ word") == "a <strong>bold</strong> and <code>code</code> and <em>italic</em> word"
    assert render_html.inline("snake_case_name stays") == "snake_case_name stays"  # underscores inside a word are not italics
    assert render_html.inline("**<i>x</i>**") == "<strong>&lt;i&gt;x&lt;/i&gt;</strong>"


def test_a_spaced_double_hyphen_is_set_as_a_dash():
    assert render_html.inline("one -- two") == "one &mdash; two" and render_html.inline("a--b") == "a--b"


def test_a_code_block_and_its_label_are_escaped_whole():
    rendered = page(("code", "bash <label>", "echo '<x>' && cat <<EOF\n**not bold** `nor code`"))
    assert '<div class="code-label">BASH &LT;LABEL&GT;</div>' in rendered
    assert "<pre><code>echo &#x27;&lt;x&gt;&#x27; &amp;&amp; cat &lt;&lt;EOF\n**not bold** `nor code`</code></pre>" in rendered


def test_a_table_marks_monospaced_cells_and_ignores_the_pdf_column_widths():
    rendered = page(("table", ["A", "B"], [["plain **bold**", "MONO:x < y"]], [100, 200]))
    assert "<th>A</th><th>B</th>" in rendered
    assert "<td>plain <strong>bold</strong></td><td class=\"mono\">x &lt; y</td>" in rendered
    assert "100" not in rendered.split("<table>")[1]


def test_the_two_kinds_of_list_and_of_callout():
    rendered = page(("ul", ["a", "b"]), ("ol", ["c"], True), ("ol", ["d"], False), ("callout", "T", "body"), ("callout_warn", "W", "careful"))
    assert "<ul><li>a</li><li>b</li></ul>" in rendered and "<ol><li>c</li></ol>" in rendered and "<ul><li>d</li></ul>" in rendered
    assert '<div class="callout"><strong>T</strong><p>body</p></div>' in rendered
    assert '<div class="callout warn"><strong>W</strong><p>careful</p></div>' in rendered


def test_a_block_kind_nobody_taught_the_page_is_an_error_not_silently_dropped():
    with pytest.raises(ValueError, match="unknown content block kind 'hologram'"):
        page(("hologram", "x"))


def test_a_source_that_is_a_bare_address_is_a_link_and_one_that_is_not_is_text():
    rendered = render_html.build(content(SOURCES=[("truffle.net", "the site"), ("Some Docs; Other Docs", None), ("a.b/c d", "no")]), style="")
    assert '<a href="https://truffle.net">truffle.net</a></strong> &mdash; the site' in rendered
    assert "<li><strong>Some Docs; Other Docs</strong></li>" in rendered
    assert 'href="https://a.b/c d"' not in rendered


# --- the page loads nothing ----------------------------------------------------------------------------

def test_the_page_loads_nothing_from_anywhere():
    rendered = render_html.build()
    assert not re.search(r"<link\b|<script\b|<img\b|<iframe\b|@import|url\(", rendered)
    assert "fonts.googleapis.com" not in rendered and "fonts.gstatic.com" not in rendered
    assert not re.search(r'\ssrc="', rendered)
    for reference in re.findall(r'href="([^"]+)"', rendered):
        assert reference.startswith(("#", "https://")), reference  # in-page anchors and the sources' own links


# --- one content, two outputs, no PDF library needed for the page ---------------------------------------

def test_the_content_and_the_page_generator_import_without_a_pdf_library(run_python):
    code = (
        "import sys\nsys.modules['reportlab'] = None  # importing it would now raise\n"
        "import dossier_content, render_html\nprint(len(render_html.build()) > 10000)\n"
    )
    result = run_python(code)
    assert result.returncode == 0 and result.stdout.strip() == "True", result.stderr


def test_the_pdf_and_the_page_share_one_content_object():
    pytest.importorskip("reportlab")
    import render_pdf

    assert render_pdf.SECTIONS is dossier_content.SECTIONS and render_pdf.SOURCES is dossier_content.SOURCES
    assert render_pdf.FOOTNOTE is dossier_content.FOOTNOTE and render_pdf.TITLE is dossier_content.TITLE
    assert render_pdf.PILLS is dossier_content.PILLS and render_pdf.SUBTITLE is dossier_content.SUBTITLE


def test_the_pdfs_column_widths_are_the_same_numbers_they_always_were():
    """dossier_content.inch stands in for reportlab's, so the widths must equal it exactly."""
    pytest.importorskip("reportlab")
    from reportlab.lib.units import inch

    assert dossier_content.inch == inch
    assert dossier_content.CW == 6.35 * inch
